
default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5

development:
  <<: *default
  database: twitter_micro_development


test:
  <<: *default
  database: twitter_micro_test


production:
  <<: *default
  database: twitter_micro_production
  host: localhost
  # url: <%= ENV["DATABASE_URL"] %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
