default: &default
  adapter: mysql2
  encoding: utf8

  pool: 5

development:
  <<: *default
  database: twitter_development


test:
  <<: *default
  database: twitter_test


production:
  <<: *default
  database: twitter_production
  host: localhost
  # url: <%= ENV["DATABASE_URL"] %>
  username: 
  password:
